image:
  tag: v0.8.0

replicas: 2

service:
  type: NodePort
  port: 80
  targetPort: 8080
  NodePort: 30001

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

