apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-role-on-dev-for-jane-sa
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: jane
    namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
