apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: kodmandvl@mail.ru
    privateKeySecretRef:
      name: myencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kodmandvl@mail.ru
    privateKeySecretRef:
      name: myencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
