apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  MINIO_ACCESS_KEY: "Dk6VtcMZdAQ=" # https://generate.plus/en/base64
  MINIO_SECRET_KEY: "krf7NZDusXotJ7JqxVGoaw==" # https://generate.plus/en/base64
