promtail:
  enabled: true
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

loki:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 6.4.1

prometheus:
  enabled: false