prometheus:
  prometheusSpec:
    tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
    
    serviceMonitorSelectorNilUsesHelmValues: false

  ingress:
    enabled: true
    annotations: {}
    ingressClassName: nginx
    hosts:
      - prometheus.158.160.134.213.nip.io
    paths:
      - /


prometheusOperator:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

prometheus-node-exporter:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule


kube-state-metrics:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

alertmanager:
  alertmanagerSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule

  ingress:
    enabled: true    
    annotations: {}

    ingressClassName: nginx
    hosts:
      - alertmanager.158.160.134.213.nip.io
    paths:
      - /

grafana:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  adminPassword: pass
  ingress:
    enabled: true    
    annotations: {}

    ingressClassName: nginx
    hosts:
      - grafana.158.160.134.213.nip.io
    paths:
      - /
      
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      jsonData:
        maxLines: 1000    